### ISSUE TITLE
Unable to resolve module `crypto` when use this module

### ISSUE THREAD

**Issue by ghost** [rhzs/hsm-pin-block#1]
crypto is depreceted but we can use crypto-js 
i cant do, but i think you can

**Comment by fardad-dev** [comment]
use this https://github.com/hosseinmd/data-crypto

**Comment by rhzs** [comment]
I don't think crypto is deprecated in latest nodejs 13. See https://nodejs.org/api/crypto.html#crypto_crypto_createcipheriv_algorithm_key_iv_options
